release:
  github:
    owner: kurehajime
    name: qrray

  header: |
    ## qrray ({{ .Date }})

    Welcome to this new release!

archives:
  - format: zip
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
      arm64: arm